### ISSUE TITLE
Add doc

### ISSUE THREAD

**Issue by Xnayak** [supabase-community/storage-dart#1]
# Bug report

## Describe the bug

Hello team , Please add any documentation or any comment . I am unable to understand which url & header you need for this. Make an example and clear that.

**Comment by awalias** [comment]
thanks for your issue @Xnayak this library is very new (3 days) and still under very heavy development, we will be sure to add the docs once it is ready to use! 👍

**Comment by inian** [comment]
Hi @Xnayak , the backend API for storage is documented [here](https://supabase.github.io/storage-api/). Let me know if something is not clear.

**Comment by dshukertjr** [comment]
Hi @Xnayak !

At the moment, you can just use the Supabase-dart library to use storage! I have used it in one of my project and it works like a charm!

**Comment by saswatsaubhagya** [comment]
@dshukertjr could you please share some examples of how you use storage with Supabase-dart?

**Comment by dshukertjr** [comment]
@saswatsaubhagya 

Of course! 
[Here](https://github.com/supabase/supabase-dart/blob/main/example/main.dart#L39) are some basic examples of how to use storage in Supabase-dart. 

[Here](https://github.com/supabase/supabase-dart/blob/main/example/main.dart#L39) are some code that I wrote that uploads a file to Supabase and gets the URL. 

If you need more example, just let me know!

**Comment by saswatsaubhagya** [comment]
@dshukertjr may i know which version you are using

**Comment by dshukertjr** [comment]
@saswatsaubhagya 
I am using `supabase: ^0.0.1-dev.13` because that was the newest version when I started creating my app. Is the current most recent version not working as expected?

BTW, I just noticed that I had shared the same link in my previous post. I meant to share [this](https://github.com/dshukertjr/spot/blob/main/lib/repositories/repository.dart#L138) link as the second example.
